### ISSUE TITLE
How to run workadventure using single-domain guide ?

### ISSUE THREAD

**Issue by pharindoko** [workadventure/workadventure#2927] opened 2022-12-29 12:49 UTC
Hey, 

tried to initially setup workadventure to just see if it works as expected following this guide:
https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/README.md

1. I renamed `.env.prod.template` to `.env`
2. execute `docker-compose -f docker-compose.prod.yaml -f docker-compose.single-domain.yaml up --build`

```bash
docker-compose -f docker-compose.prod.yaml -f docker-compose.single-domain.yaml up --build
WARN[0000] The "AWS_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PROMETHEUS_AUTHORIZATION_TOKEN" variable is not set. Defaulting to a blank string. 
[+] Running 9/9
 ⠿ Container docker-reverse-proxy-1  Created                                                                          0.1s
 ⠿ Container docker-icon-1           Created                                                                          0.1s
 ⠿ Container docker-uploader-1       Created                                                                          0.1s
 ⠿ Container docker-back-1           Created                                                                          0.1s
 ⠿ Container docker-chat-1           Created                                                                          0.1s
 ⠿ Container docker-ejabberd-1       Created                                                                          0.1s
 ⠿ Container docker-map-storage-1    Created                                                                          0.1s
 ⠿ Container docker-redis-1          Created                                                                          0.1s
 ⠿ Container docker-play-1           Created                                                                          0.1s
Attaching to docker-back-1, docker-chat-1, docker-ejabberd-1, docker-icon-1, docker-map-storage-1, docker-play-1, docker-redis-1, docker-reverse-proxy-1, docker-uploader-1
docker-icon-1           | iconserver v3.13.0 (2021-08-01) (go1.16.6) - https://github.com/mat/besticon
docker-icon-1           | server: 2022/12/29 12:46:31.454373 Starting server on 0.0.0.0:8080...
docker-chat-1           | Templating /usr/share/nginx/html/index.tpl.html
docker-chat-1           | + set -o nounset errexit
docker-chat-1           | + index_file_in=/usr/share/nginx/html/index.tpl.html
docker-chat-1           | + index_file_out=/usr/share/nginx/html/index.html
docker-chat-1           | + tmp_trackcodefile=/tmp/trackcode
docker-chat-1           | + ANALYTICS_CODE_PATH=dist/ga.html.tmpl
docker-chat-1           | + '[' NO '=' NO ]
docker-chat-1           | + echo 
docker-chat-1           | + '['  '!='  ]
docker-chat-1           | + '[' NO '!=' NO ]
docker-chat-1           | + echo 'Templating /usr/share/nginx/html/index.tpl.html'
docker-chat-1           | + sed '/<!-- TRACK CODE -->/r /tmp/trackcode' /usr/share/nginx/html/index.tpl.html
docker-chat-1           | + rm /tmp/trackcode
docker-chat-1           | + md5sum /usr/share/nginx/html/env-config.js
docker-chat-1           | + set -- 011ec5eaf9cb99b6337d1627d3b85f8f /usr/share/nginx/html/env-config.js
docker-chat-1           | + md5=011ec5eaf9cb99b6337d1627d3b85f8f
docker-chat-1           | + cp /usr/share/nginx/html/env-config.js /usr/share/nginx/html/env-config.011ec5eaf9cb99b6337d1627d3b85f8f.js
docker-chat-1           | + sed -i s/env-config.js/env-config.011ec5eaf9cb99b6337d1627d3b85f8f.js/g /usr/share/nginx/html/index.html
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: using the "epoll" event method
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: nginx/1.21.6
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: OS: Linux 4.14.276-211.499.amzn2.x86_64
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 32768:65536
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: start worker processes
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: start worker process 17
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: start worker process 18
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: start worker process 19
docker-chat-1           | 2022/12/29 12:46:32 [notice] 1#1: start worker process 20
docker-redis-1          | 1:C 29 Dec 2022 12:46:32.670 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
docker-redis-1          | 1:C 29 Dec 2022 12:46:32.675 # Redis version=6.2.8, bits=64, commit=00000000, modified=0, pid=1, just started
docker-redis-1          | 1:C 29 Dec 2022 12:46:32.675 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.676 * monotonic clock: POSIX clock_gettime
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.680 * Running mode=standalone, port=6379.
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 # Server initialized
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 * Loading RDB produced by version 6.2.8
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 * RDB age 13 seconds
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 * RDB memory usage when created 0.77 Mb
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 # Done loading RDB, keys loaded: 0, keys expired: 0.
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 * DB loaded from disk: 0.000 seconds
docker-redis-1          | 1:M 29 Dec 2022 12:46:32.681 * Ready to accept connections
docker-reverse-proxy-1  | time="2022-12-29T12:46:33Z" level=info msg="Configuration loaded from flags."
docker-reverse-proxy-1  | time="2022-12-29T12:46:33Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
docker-map-storage-1    | 
docker-map-storage-1    | > map-storage@1.0.0 start /usr/src/map-storage
docker-map-storage-1    | > ts-node --transpileOnly ./src/index.ts
docker-map-storage-1    | 
docker-ejabberd-1       | 2022-12-29 12:46:37.170096+00:00 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
docker-ejabberd-1       | 2022-12-29 12:46:37.738108+00:00 [notice] Changing loglevel from 'info' to 'warning'
docker-uploader-1       | 
docker-uploader-1       | > workadventureuploader@1.0.0 start /usr/src/uploader
docker-uploader-1       | > ts-node --transpileOnly ./server.ts
docker-uploader-1       | 
docker-play-1           | 
docker-play-1           | > workadventure-play@1.0.0 start /usr/src/play
docker-play-1           | > TS_NODE_PROJECT=tsconfig-pusher.json ts-node --transpileOnly ./src/server.ts
docker-play-1           | 
docker-back-1           | 
docker-back-1           | > workadventureback@1.0.0 runprod /usr/src/back
docker-back-1           | > ts-node --transpileOnly ./server.ts
docker-back-1           | 
docker-uploader-1       | WorkAdventure uploader starting on port 8080!
docker-reverse-proxy-1  | time="2022-12-29T12:46:44Z" level=error msg="Unable to obtain ACME certificate for domains \"localhost\": unable to generate a certificate for the domains [localhost]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"localhost\": Domain name needs at least one dot" rule="Host(`localhost`) && PathPrefix(`/api`)" providerName=myresolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=back-ssl@docker
docker-ejabberd-1       | 2022-12-29 12:46:49.367186+00:00 [warning] Mnesia backend for mod_mam is not recommended: it's limited to 2GB and often gets corrupted when reaching this limit. SQL backend is recommended. Namely, for small servers SQLite is a preferred choice because it's very easy to configure.
docker-ejabberd-1       | 2022-12-29 12:46:53.449052+00:00 [warning] Invalid certificate in /opt/ejabberd/conf/server.pem: at line 53: self-signed certificate
docker-map-storage-1    | Application is running on port 3000
docker-map-storage-1    | Application is running
docker-map-storage-1    | gRPC port is 50053
docker-ejabberd-1       | :> ejabberdctl register admin ejabberd.workadventure.localhost mySecretPassword
docker-ejabberd-1       | User admin@ejabberd.workadventure.localhost successfully registered
docker-reverse-proxy-1  | time="2022-12-29T12:47:02Z" level=error msg="Unable to obtain ACME certificate for domains \"localhost\": unable to generate a certificate for the domains [localhost]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"localhost\": Domain name needs at least one dot" rule="Host(`localhost`) && PathPrefix(`/map-storage`)" routerName=map-storage-ssl@docker ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme
docker-play-1           | Errors found in environment variables:
docker-play-1           | For variable "SECRET_KEY": String must contain at least 1 character(s)
docker-play-1           | For variable "PUSHER_URL": Invalid url
docker-play-1           | For variable "UPLOADER_URL": Invalid url
docker-play-1           | For variable "ICON_URL": Invalid url
docker-play-1           | For variable "CHAT_URL": Invalid url
docker-play-1           | For variable "OPID_WOKA_NAME_POLICY": Invalid enum value. Expected 'user_input' | 'allow_override_opid' | 'force_opid', received ''
docker-play-1           |  ELIFECYCLE  Command failed with exit code 1.
docker-play-1 exited with code 1
docker-back-1           | WorkAdventure HTTP API starting on port 8080!
docker-back-1           | Error connecting to Redis: ConnectionTimeoutError: Connection timeout
docker-back-1           |     at Socket.<anonymous> (/usr/src/node_modules/.pnpm/@redis+client@1.4.2/node_modules/@redis/client/dist/lib/client/socket.js:164:124)
docker-back-1           |     at Object.onceWrapper (node:events:627:28)
docker-back-1           |     at Socket.emit (node:events:513:28)
docker-back-1           |     at Socket.emit (node:domain:489:12)
docker-back-1           |     at Socket._onTimeout (node:net:562:8)
docker-back-1           |     at listOnTimeout (node:internal/timers:564:17)
docker-back-1           |     at processTimers (node:internal/timers:507:7)
docker-back-1           | CPU high threshold alert. Going in "overheat" mode
docker-back-1           | WorkAdventure HTTP/2 API starting on port 50051!
docker-back-1           | (node:19) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
docker-back-1           | (Use `node --trace-deprecation ...` to show where the warning was created)
docker-back-1           | Redis client is reconnecting
docker-back-1           | Redis client is connected
docker-back-1           | Redis client is ready
docker-back-1           | CPU is back to normal. Canceling "overheat" mode
docker-play-1           | 
docker-play-1           | > workadventure-play@1.0.0 start /usr/src/play
docker-play-1           | > TS_NODE_PROJECT=tsconfig-pusher.json ts-node --transpileOnly ./src/server.ts
docker-play-1           | 
```

Do I need to setup additional properties for let`s encrypt ?

**Comment by pharindoko** [comment] 2023-01-05 07:16
@moufmouf does it work for you as expected ?

**Comment by pharindoko** [comment] 2023-01-10 15:59
Please guys, can anyone help ? @moufmouf  @gparant 
I try to run the single-domain docker-compose on a aws ec2 with amazon linux 2 and want to be able to open it in my browser.
Do I have to add additional settings like this AWS_URL env variable ?

**Comment by moufmouf** [comment] 2023-01-10 21:25
Weird... look at the errors for the "play" container.

In `.env` you MUST set a "SECRET_KEY". Any random string will be ok.

Also, I notice that you need to set `OPID_WOKA_NAME_POLICY` to any valid value (like `user_input`).
I actually need to change that.

Finally, regarding PUSHER_URL, UPLOADER_URL, ICON_URL and CHAT_URL, these values should be ok (I'm not reproducing the errors you have).

Maybe try to run a "docker-compose pull" to download the latest version of the images?

**Comment by pharindoko** [comment] 2023-01-10 23:19
Thanks @moufmouf for the feedback. Will try it tomorrow...

**Comment by ercanucan** [comment] 2023-01-13 16:02
@moufmouf are these "invalid url" messages expected? i see a similar behavior. Even though I pass in those variables in my docker compose file, the play container gets stuck in a crash/restart loop with this message.

```
play-1           | Errors found in environment variables:
play-1           | For variable "UPLOADER_URL": Invalid url
play-1           | For variable "ICON_URL": Invalid url
play-1           | For variable "CHAT_URL": Invalid url
```

section from my docker compose file (I do not here use .env, directly pass the variables)
```
play:
  image: thecodingmachine/workadventure-play:v1.14.13
  environment:
    ...
    - ICON_URL=/icon
    - CHAT_URL=/chat
    - UPLOADER_URL=/uploader
    ...
```

`docker inspect` tells me that the env variables are passed in correctly (a section from that):
```
   "UPLOADER_URL=/uploader",
   "ICON_URL=/icon",
   "CHAT_URL=/chat"
```

I'm wondering what I might be missing here or this is expected. Thx!

**Comment by zobadaniel** [comment] 2023-01-18 15:15
I had the same issue with the environment variables, when using a release version of the docker containers.
However, building from source as of today got rid of the errors. 
I'm having different issues now that prevent the single-domain config to work for me, but at least not this one.

**Comment by saschafoerster** [comment] 2023-01-23 22:14
I am also fiddling around with this issues since a lot of versions, I spent weeks to find a version that works for my, but with the latest changes in chat, everything is broken again. I wish there was a docker-compose.yml that is made with this as background: 
- there is one .env file with all needed variables
- there is one docker-compose.yml with everything needed to run workadventure self hosted. 
- just a simple "docker-compose up -d" brings up everything, when .env settings are correct 
- it should respect, that there are other services running on the same machine using port 80 and 443, for instance an nginx-proxy, this ports should not be used by the docker container or be mandatory 
- a separate nginx proxy then can just proxy to a port that is not 80 or 443 but something random like 8080, which is the main entry point. Maybe some nginx-configuration example would be nice, if there is a web socket for instance
- the docker-compose file should not take care of SSL, this is the job of the separate nginx proxy and certbot on the machine 
- the docker-compose file should use existing images (maybe it could be an option to build them yourselves, hidden behind #)
- everything should directly work as a single domain installation with subdirectories and not subdomains 
- maps are stored elsewhere, so no need to spin up another webserver for that, only optionally

I think that would make it much easier to use our docker-compose-examples in most scenarios. At least that's how most docker-compose.yml I have seen are constructed. 

Here, there are so many settings I don't fulfill: I don't have subdomains, I don't want to use traefic as proxy and I don't want to let a single docker container use port 80 and 443. It's a mess to change everything to a "normal" docker-compose.yml. 

Of course I would be happy if anyone could share his actual working docker-compose.yml (with the descriptions I made) :)

**Comment by zobadaniel** [comment] 2023-01-25 06:42
For me personally, having a single-domain config with HTTP only would be sufficient. I can "hide" traefik behind Nginx Proxy Manager, who will also take care of certificates. I have one old working such config (ok chat is broken) before container restructure ("play"). I failed to bring it up to date, 'cause I don't know traefik. I hope I'm not stuck with an outdated install forever.

I can understand that the support for self-hosting is limited, because enabling people to self-host is not gonna make money for the company at all. Still I wish the config was not so difficult to comprehend.

**Comment by fingolfin** [comment] 2024-01-18 13:56
Commit message of cfd6debb823ba018742d68fe4e9390ae49ca569c says:

> Improving documentation regarding self-hosting
> - Adding detailed instructions to install WorkAdventure
> - Removing the multi-domain install => we now support only one install: the single-domain one
> 
> This single-domain install is well tested via CI.


So maybe this issue is resolved?

**Comment by zobadaniel** [comment] 2024-01-18 14:47
Works for me now. Could be closed if there are no other objections.

**Comment by moufmouf** [comment] 2024-01-18 16:07
Cool! Closing this. Don't hesitate to open a new issue if other issues arise!

**Closed by moufmouf** 2024-01-18 16:07 UTC
Labels: question
